name: Deploy to EC2

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude='.git*' ./ ubuntu@${{ secrets.EC2_IP_ADDRESS }}:RemoteGateWay

      - name: Ensure restart script is executable
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} 'chmod +x RemoteGateWay/restart_script.sh'

      - name: Restart application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} 'RemoteGateway/restart_script.sh'
